skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
presale = "6t8hLg3DvTYzXkm3gfNhMfgqh2x1akjjM2zwv8SMprA3"

[provider]
cluster = "devnet"
wallet = "/home/wingleman-sonata/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
